services:
  react:
    build:
      args:
        - NODE_VER=20.16.0
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./thining-in-react:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173

volumes:
  node_modules:
